server:
  port: 8080

spring:
  profiles:
    include: ovsx
  datasource:
    url: jdbc:postgresql://pgsql-server:5432/postgres
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never

  security:
      oauth2:
        client:
          registration:
            github:
              client-id: 606ef09ae1ac527b8350
              client-secret: 5f4377e330b0b8c9ef05d06680a6641352f3f0ff

management:
  health:
    probes:
      enabled: true

ovsx:
  databasesearch:
    enabled: true
  elasticsearch:
    enabled: false
  eclipse:
    base-url: https://api.eclipse.org
    publisher-agreement:
      timezone: US/Eastern
  upstream:
    url: https://open-vsx.org/
  webui:
    url: http://localhost:3000
  storage:
    azure:
      service-endpoint: https://smarideopenvsx.blob.core.windows.net/
      sas-token: ?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2024-11-21T00:25:34Z&st=2022-04-07T16:25:34Z&sip=127.0.0.1-255.255.225.0&spr=https,http&sig=ih7wAnnkXMZBCJgQmCcVNONFiDo0RC%2BJx1zvqhwRmzQ%3D