name: SmartIDE-OpenVSX-Image-Build-CI

on:
  push:
    branches:    
      - master
    paths: 
      - deployment/smartide-image/**
      - .github/workflows/smartide-openvsx-image.yml

env:
  IMAGE_NAME: smartide-openvsx
  ALIYUN_IMAGE_REGISTRY: registry.cn-hangzhou.aliyuncs.com
  IMAGE_REGISTRY_NAMESPACE: smartide

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set Image Version
      run: echo "IMAGE_VERSION=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
    - name: Build Image
      run: docker build -t $IMAGE_NAME:$IMAGE_VERSION deployment/smartide-image
    - name: DockerHub Image Tags
      run: |
        docker tag $IMAGE_NAME:$IMAGE_VERSION $IMAGE_REGISTRY_NAMESPACE/$IMAGE_NAME:$IMAGE_VERSION
    - name: Push DockerHub
      run: |
        echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} --password-stdin
        docker push $IMAGE_REGISTRY_NAMESPACE/$IMAGE_NAME:$IMAGE_VERSION
    - name: Aliyun Image Tags
      run: |
        docker tag $IMAGE_NAME:$IMAGE_VERSION $ALIYUN_IMAGE_REGISTRY/$IMAGE_REGISTRY_NAMESPACE/$IMAGE_NAME:$IMAGE_VERSION
    - name: Push Aliyun
      run: |
        echo ${{ secrets.ALIYUN_PASSWORD }} | docker login $ALIYUN_IMAGE_REGISTRY -u ${{ secrets.ALIYUN_LOGIN }} --password-stdin
        docker push $ALIYUN_IMAGE_REGISTRY/$IMAGE_REGISTRY_NAMESPACE/$IMAGE_NAME:$IMAGE_VERSION
