name: SmartIDE-Openvsx-Extensions-Sync

on:
  push:
    branches:    
      - smartide-marketplace
    paths: 
      - publish-extensions/sync-extensions.js
      - .github/workflows/smartide-openvsx-extensions-sync.yml
  schedule:
    - cron: "0 0 * * *"
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: cschleiden/replace-tokens@v1
      with:
        files: '["publish-extensions/package.json"]'
      env:
        OVSX_PAT: ${{ secrets.OVSX_PAT }}
        OVSX_REGISTRY_URL: ${{ secrets.OVSX_REGISTRY_URL }}
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Npm Install
      run: npm install 
      working-directory: publish-extensions
    - name: Npm run sync
      run: npm run sync
      working-directory: publish-extensions